<?php

namespace Database\Seeders;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UsersSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::create(['name' => 'Steve', 'email' => 'stevykana21@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/21/1993')]);
        User::create(['name' => 'Hamza', 'email' => 'farajihamza18@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('6/17/2008')]);
        User::create(['name' => 'Kevin', 'email' => 'stevykana@yahoo.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/21/1993')]);
        User::create(['name' => 'Rafael', 'email' => 'elchris2035@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/17/1992')]);
        User::create(['name' => 'neha', 'email' => 'walidchoukri96@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/2/1996')]);
        User::create(['name' => 'Dorian', 'email' => 'garibaldi.merck@hotmail.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/20/1999')]);
        User::create(['name' => 'Laure', 'email' => 'laure.conrad@outlook.fr', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('3/10/2000')]);
        User::create(['name' => 'winnery', 'email' => 'hop.gangnam.style@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('2/15/1996')]);
        User::create(['name' => 'Diane', 'email' => 'vanina.duncan@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('2/1/1989')]);
        User::create(['name' => 'S.K.', 'email' => 'steve-kevin.kana-tsafack@grenoble-em.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/27/2000')]);
        User::create(['name' => 'Joan', 'email' => 'jjkenfack@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/19/2000')]);
        User::create(['name' => 'Tr\u00e9sor', 'email' => 'laluz697@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('2/1/2000')]);
        User::create(['name' => 'Harold MBING MOULELA', 'email' => 'haroldmoulela@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/5/1997')]);
        User::create(['name' => 'Kiruaaa', 'email' => 'riham.lara.hafsia@icloud.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('9/7/2002')]);
        User::create(['name' => 'Hiroko', 'email' => 'owo.mineko@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/6/2003')]);
        User::create(['name' => 'Marius', 'email' => 'mariuschevalerias@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/4/2006')]);
        User::create(['name' => 'toyo350zz', 'email' => 'theoboudjema1@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/26/2001')]);
        User::create(['name' => 'DeadCrow', 'email' => 'pcgsky666@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/20/1998')]);
        User::create(['name' => 'passio', 'email' => 'mister-jo83@hotmail.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/22/1998')]);
        User::create(['name' => 'Louqmane', 'email' => 'louqmane30200@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/7/2005')]);
        User::create(['name' => 'Arthur \/\/ Acleefr', 'email' => 'arthur@aclee.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/15/1999')]);
        User::create(['name' => 'Fresh', 'email' => 'allan.roussel@live.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/23/1993')]);
        User::create(['name' => 'moi', 'email' => 'giugiulana2@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('9/4/2005')]);
        User::create(['name' => 'Ba', 'email' => 'abdineba25@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/19/2000')]);
        User::create(['name' => 'lvneso', 'email' => 'yaina765@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('2/15/1999')]);
        User::create(['name' => 'Mattis', 'email' => 'mattismassoni@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('3/4/2001')]);
        User::create(['name' => 'Tristan POMMERY', 'email' => 'tristan.pommery@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('3/20/2000')]);
        User::create(['name' => 'heydwaard', 'email' => 'heydwaard@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('4/17/2004')]);
        User::create(['name' => 'Sol\u00e8ne', 'email' => 'diant.sol@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('9/3/2003')]);
        User::create(['name' => 'ilixne2z', 'email' => 'vegetozvlg92i@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/30/2006')]);
        User::create(['name' => 'Lucas', 'email' => 'luba@orange.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('4/11/2000')]);
        User::create(['name' => 'Julien', 'email' => 'jteracketenchausette@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/26/2000')]);
        User::create(['name' => 'Bart', 'email' => 'paul.barthelemy@outlook.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('9/4/1999')]);
        User::create(['name' => 'Nami', 'email' => 'mennimessa@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('1/3/2002')]);
        User::create(['name' => 'Kervaut', 'email' => 'Kdavid44000@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/27/1999')]);
        User::create(['name' => 'Ben', 'email' => 'zied.twitter@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/7/1982')]);
        User::create(['name' => 'Gab', 'email' => 'bm.gabrielsoudry@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('9/7/2000')]);
        User::create(['name' => 'Vita', 'email' => 'amandinevaillant0304@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('5/3/2001')]);
        User::create(['name' => 'Lunso', 'email' => 'lvnesoleil@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('2/2/1999')]);
        User::create(['name' => 'Cajou', 'email' => 'cajouit@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/20/2004')]);
        User::create(['name' => 'lucasssp66', 'email' => 'guiillaumep226@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/26/2003')]);
        User::create(['name' => 'hugz', 'email' => 'hugo.fully@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/9/2000')]);
        User::create(['name' => '^^', 'email' => 'nizardadsi@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('2/1/2001')]);
        User::create(['name' => 'Sami Miteul', 'email' => 'samiteul10@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/7/2006')]);
        User::create(['name' => 'Ozan', 'email' => 'kiwwixxyt@hotmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/8/2002')]);
        User::create(['name' => 'Nabss', 'email' => 'xopoi@yopmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/4/1966')]);
        User::create(['name' => 'Hugo', 'email' => 'hsantimaria@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('4/6/2004')]);
        User::create(['name' => 'Lina', 'email' => 'khaylina455@icloud.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('3/4/2005')]);
        User::create(['name' => 'ay', 'email' => 'ayoubrbh1902@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('2/19/2001')]);
        User::create(['name' => 'Cupcake', 'email' => 'dodobebou8@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('6/12/2007')]);
        User::create(['name' => 'aicha', 'email' => 'dehayeaicha@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('4/9/2004')]);
        User::create(['name' => 'Marchand', 'email' => 'teufo.0123@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/7/1999')]);
        User::create(['name' => 'Theo', 'email' => 'theodubret@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/4/2003')]);
        User::create(['name' => 'C moi wsh', 'email' => 'denisetbaloo@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/1/1900')]);
        User::create(['name' => 'Simon', 'email' => 'sicoutier@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/3/2003')]);
        User::create(['name' => 'sarah', 'email' => 'salutcwsh17@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('1/26/2004')]);
        User::create(['name' => 'Gablebgnnmdr', 'email' => 'rerevi7212@1adir.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/6/2004')]);
        User::create(['name' => 'Kylian', 'email' => 'leduckylian5@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/13/2001')]);
        User::create(['name' => 'Robert Leo', 'email' => 'robert.leo.pro@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/3/2001')]);
        User::create(['name' => 'Marguerite Yager', 'email' => 'marguerite.yager@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('4/23/2005')]);
        User::create(['name' => 'Romain', 'email' => 'rororomain22@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('9/12/2002')]);
        User::create(['name' => 'Salom\u00e9', 'email' => 'christinaakyr@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('10/1/2002')]);
        User::create(['name' => 'Lucassss', 'email' => 'thisinsane1@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/12/2005')]);
        User::create(['name' => 'Justin', 'email' => 'justin.demoulin51@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/5/2006')]);
        User::create(['name' => 'Bouilloncube', 'email' => 'bigorno.31800@outlook.fr', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('4/3/2002')]);
        User::create(['name' => 'RiyukTu', 'email' => 'test20032010@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/12/2003')]);
        User::create(['name' => 'Leo', 'email' => 'hardwaregame.fr@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/11/2000')]);
        User::create(['name' => 'Dekali', 'email' => 'kenzo.dekali@outlook.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/7/2003')]);
        User::create(['name' => '\ud835\udc75\ud835\udc9a\ud835\udc99', 'email' => 'jesuispasnyx@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/11/2002')]);
        User::create(['name' => 'Chlo\u00e9', 'email' => 'chloegatuo@outlook.fr', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('6/18/2003')]);
        User::create(['name' => 'Zo\u00e9', 'email' => 'futicraftuwu@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('1/13/2009')]);
        User::create(['name' => 'liassinne', 'email' => 'Kenshiro.landers@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/12/1994')]);
        User::create(['name' => 'Itadori', 'email' => 'kdekali14@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/7/2003')]);
        User::create(['name' => 'Feu de bois', 'email' => 'yahooyaya1234@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('12/21/2005')]);
        User::create(['name' => 'Mathieu', 'email' => 'atomze78@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/20/2003')]);
        User::create(['name' => '$$', 'email' => 'skillgalaxyforever@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/16/2000')]);
        User::create(['name' => 'Erblin', 'email' => 'erblincsi@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/21/2000')]);
        User::create(['name' => 'Jujute petasse', 'email' => 'lolipopkikoo@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('8/17/1945')]);
        User::create(['name' => 'Ayoub', 'email' => 'ayoubhelal144@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/9/2000')]);
        User::create(['name' => 'Mehdi Belkrial', 'email' => 'mahdibelkrial7@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/23/2005')]);
        User::create(['name' => 'maat PAKIRY', 'email' => 'maatpakiry93@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('9/20/2001')]);
        User::create(['name' => 'SAMUEL', 'email' => 'samouyte@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/23/2005')]);
        User::create(['name' => 'Tristan', 'email' => 'tristan.daniel@outlook.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/20/2000')]);
        User::create(['name' => 'Chams Adam', 'email' => 'adamchams@outlook.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/7/2001')]);
        User::create(['name' => 'Arouf', 'email' => 'aroufdu77@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('3/6/2002')]);
        User::create(['name' => 'Shera \ud83d\udc1d', 'email' => 'chahrazed.belkharroubi34@hotmail.fr', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('3/25/1996')]);
        User::create(['name' => 'Picard', 'email' => 'simsimpic59@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('12/12/2005')]);
        User::create(['name' => 'Annabelle', 'email' => 'annabelleperrinleborgne@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('11/14/2004')]);
        User::create(['name' => 'Malooooooooooooooo', 'email' => 'biduleman06@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/9/1998')]);
        User::create(['name' => 'Levi', 'email' => 'uxjfjdj@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/1/2001')]);
        User::create(['name' => 'Aoui270', 'email' => '1978aoui@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/2/2005')]);
        User::create(['name' => 'Enzo', 'email' => 'enzolevy95@hotmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('4/16/2003')]);
        User::create(['name' => 'Joseph', 'email' => 'Naveenjoseph@hotmail.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/26/2000')]);
        User::create(['name' => 'Valentin', 'email' => 'moitievalentin@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/5/2002')]);
        User::create(['name' => 'Aghiles', 'email' => 'aqwwqa963@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/5/2004')]);
        User::create(['name' => 'Elias', 'email' => 'elias_2408@hotmail.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/1/1996')]);
        User::create(['name' => 'cl\u00e9ment busson', 'email' => 'bussclem@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/7/1998')]);
        User::create(['name' => 'Alicia', 'email' => 'aliciaprtgl04@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('4/21/2002')]);
        User::create(['name' => 'Je te soutiens', 'email' => 'emersone.beneli@outlook.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/30/2003')]);
        User::create(['name' => 'Gourmand', 'email' => 'enes67_zonguldak@hotmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/4/2001')]);
        User::create(['name' => 'Leleu Gauthier', 'email' => 'gauthierleleu14@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/4/2001')]);
        User::create(['name' => 'Kentzz', 'email' => 'quentinwalter22@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/29/2000')]);
        User::create(['name' => 'toma', 'email' => 'duffmanytb@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/18/2003')]);
        User::create(['name' => 'Puiprzz', 'email' => 'ruifcpsg@hotmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/11/2005')]);
        User::create(['name' => 'flo', 'email' => 'florian.gj.ramon@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('9/12/2002')]);
        User::create(['name' => 'Eren', 'email' => 'nagarali01@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/20/2003')]);
        User::create(['name' => 'rio999', 'email' => 'peschilario8@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/7/2001')]);
        User::create(['name' => 'Aslan', 'email' => 'pinkbubble1509@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('3/9/2003')]);
        User::create(['name' => 'val', 'email' => 'valoumeens@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/27/2003')]);
        User::create(['name' => 'Kiyan38_8', 'email' => 'kiyan38130@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('9/29/2002')]);
        User::create(['name' => 'Tom', 'email' => 'tom.rivillon@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/2/2004')]);
        User::create(['name' => 'Thomas', 'email' => 'gannetthomas@orange.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/5/2002')]);
        User::create(['name' => 'Sofian', 'email' => 'stevbrt604@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/4/2001')]);
        User::create(['name' => 'Peiro', 'email' => 'kevinsama69330@yahoo.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('2/8/1990')]);
        User::create(['name' => 'Kira', 'email' => 'bensalmiarayane@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/28/2005')]);
        User::create(['name' => 'Bilou', 'email' => 'billalabdali@icloud.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('8/6/2002')]);
        User::create(['name' => 'Yasine', 'email' => 'antoine@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/5/2000')]);
        User::create(['name' => 'Henri', 'email' => 'stelmaszak.henri@orange.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/12/2005')]);
        User::create(['name' => 'Whitesnake93', 'email' => 'youssefb933@hotmail.fr', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('10/7/2003')]);
        User::create(['name' => 'Gabriel', 'email' => 'gabrielfleury150@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/1/2005')]);
        User::create(['name' => 'Thobay', 'email' => 'thomasbayou76@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/8/2001')]);
        User::create(['name' => 'Ed', 'email' => 'bingue.mederic@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/25/2000')]);
        User::create(['name' => 'Clem', 'email' => 'clemence.la.fraise@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('1/7/2001')]);
        User::create(['name' => 'Noe', 'email' => 'noeheiserdlc1909@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('9/19/2005')]);
        User::create(['name' => 'Illu', 'email' => 'noefabre301101@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/30/2001')]);
        User::create(['name' => 'J\u2019mennuie', 'email' => 'azerty741258@hotmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('3/3/2001')]);
        User::create(['name' => 'jdiipaa', 'email' => 'vvjvxfgh@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/1/2003')]);
        User::create(['name' => 'palala', 'email' => 'moufakkir95@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/22/2004')]);
        User::create(['name' => 'Amina', 'email' => 'aminaa.pro@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('6/12/2004')]);
        User::create(['name' => 'Alise', 'email' => 's.tacchni357@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('4/10/1998')]);
        User::create(['name' => 'Angel', 'email' => 'carbonangel837@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/15/2001')]);
        User::create(['name' => 'Bourgois', 'email' => 'evanbourgois0001@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('12/17/2003')]);
        User::create(['name' => 'Evan', 'email' => 'evanbourgois1000@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('12/17/2003')]);
        User::create(['name' => 'Durant', 'email' => 'YOUSSOUFA69@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/21/1997')]);
        User::create(['name' => 'Lila', 'email' => 'roxanneaxelle98@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('9/6/1998')]);
        User::create(['name' => 'Aris', 'email' => 'arislalouni@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/23/2004')]);
        User::create(['name' => 'Kady', 'email' => 'ekra.laurettekady2005@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('1/28/2005')]);
        User::create(['name' => 'Leila', 'email' => 'alaouilinamt2@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('1/4/2000')]);
        User::create(['name' => 'Incoo', 'email' => 'erwan.d951@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('12/8/1996')]);
        User::create(['name' => 'quentinux', 'email' => 'gydr.quentin@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/5/2001')]);
        User::create(['name' => 'SihamDZZ', 'email' => 'siham_pannese@outlook.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/2/2000')]);
        User::create(['name' => 'Otto', 'email' => 'michmouch54321@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/24/2001')]);
        User::create(['name' => 'Ethan', 'email' => 'ethan.claude@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('9/10/2002')]);
        User::create(['name' => 'Debby', 'email' => 'black2542@hotmail.fr', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('4/25/2000')]);
        User::create(['name' => 'lil\'yas', 'email' => 'kopstslo@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/25/1998')]);
        User::create(['name' => 'Cleminsky', 'email' => 'clement.cirillo1@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('3/28/2001')]);
        User::create(['name' => 'Elias la menace', 'email' => 'eliasleboucher14@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/14/2003')]);
        User::create(['name' => 'Culpaaa', 'email' => 'lina.2111130.auxonne@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('1/7/2004')]);
        User::create(['name' => 'Anais', 'email' => 'zminka.anais@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('12/8/2001')]);
        User::create(['name' => 'ouillet', 'email' => 'injustice.tutos@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/29/2000')]);
        User::create(['name' => 'Bj', 'email' => 'vji@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/6/2000')]);
        User::create(['name' => 'Zo', 'email' => 'rakaleking@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/7/2002')]);
        User::create(['name' => 'Yanis', 'email' => 'y.ouztitchaize@free.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('12/7/2001')]);
        User::create(['name' => 'L\u00e9ane', 'email' => 'leanebourgogne58@hotmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('8/16/2001')]);
        User::create(['name' => 'Karim l\'exil\u00e9', 'email' => 'karimdrawdela@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/30/2002')]);
        User::create(['name' => 'Mathias', 'email' => 'tatasse911@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/7/2002')]);
        User::create(['name' => 'Quentin', 'email' => 'starlinator06@live.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('3/7/2001')]);
        User::create(['name' => 'Bin', 'email' => 'bingray1024@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/1/2002')]);
        User::create(['name' => 'Devi Filippi', 'email' => 'filippdevi@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('2/20/2002')]);
        User::create(['name' => 'Cassandre', 'email' => 'prismemanga@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('3/3/2005')]);
        User::create(['name' => 'christophe', 'email' => 'christophe91310@live.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('9/30/1996')]);
        User::create(['name' => 'Saaamiiiaa', 'email' => 'samia.nj.00@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('8/10/1997')]);
        User::create(['name' => 'Le_kB9', 'email' => 'momo27412@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/29/1999')]);
        User::create(['name' => 'Ksy', 'email' => 'tyssou11@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('9/25/2005')]);
        User::create(['name' => 'Thomas Graindorge', 'email' => 'graindorgethomas1@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/10/1998')]);
        User::create(['name' => 'Aim\u00e9e Schmitt', 'email' => 'aimeesmt1@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('1/3/2002')]);
        User::create(['name' => 'alba', 'email' => 'vladguelai@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('3/13/2000')]);
        User::create(['name' => 'Kalido', 'email' => 'kalidolkn@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('4/19/2004')]);
        User::create(['name' => 'Le\u00efla TOUMELIN', 'email' => 'eleiltoum@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('10/27/1997')]);
        User::create(['name' => 'Enzo Guetny', 'email' => 'enzo.guetny@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/24/2003')]);
        User::create(['name' => 'Ga\u00ebl', 'email' => 'letsar3@yahoo.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/3/1981')]);
        User::create(['name' => 'Greg', 'email' => 'lebigboss.maryanyan@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/21/2000')]);
        User::create(['name' => 'Alexandrin', 'email' => 'psp.tqtlami@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/6/2000')]);
        User::create(['name' => 'Bastien', 'email' => 'hugotqtsa@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/6/2000')]);
        User::create(['name' => 'Teena', 'email' => 'laimenerania@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('12/10/2000')]);
        User::create(['name' => 'Lucas Monvois', 'email' => 'lucasmnvs@yahoo.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/17/2002')]);
        User::create(['name' => 'Sina\u00ef', 'email' => 'judupres17@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('3/5/1945')]);
        User::create(['name' => 'Kenza', 'email' => 'usaidmoyo@gmail.Com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('1/23/2000')]);
        User::create(['name' => 'test test', 'email' => 'test001@yopmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/13/2000')]);
        User::create(['name' => 'tg', 'email' => 'tg.stp@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('9/11/2005')]);
        User::create(['name' => 'Men', 'email' => 'enzosaintlouis745@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/15/2004')]);
        User::create(['name' => 'Amir', 'email' => 'boutalebamir@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('3/19/2001')]);
        User::create(['name' => 'Amyr', 'email' => 'amir.boutaleb75@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('3/19/2001')]);
        User::create(['name' => 'Forzak', 'email' => 'forzak8@mail.ch', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/2/1998')]);
        User::create(['name' => 'Marty', 'email' => 'lenaic.thomas519@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/1/1999')]);
        User::create(['name' => 'Mormox', 'email' => 'mormox.930@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/13/2000')]);
        User::create(['name' => 'Alexandre', 'email' => 'aleks54000@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('4/27/2000')]);
        User::create(['name' => 'Fernandez', 'email' => 'steffana.fernandez@icloud.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('5/9/2001')]);
        User::create(['name' => 'zatem', 'email' => 'mathieu1beau@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/1/2001')]);
        User::create(['name' => 'Yay', 'email' => 'pierrecommelarocks@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/14/2005')]);
        User::create(['name' => 'William', 'email' => 'william00.jolivet@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/31/2005')]);
        User::create(['name' => 'Gomes', 'email' => 'josegrace.gomes@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/23/1994')]);
        User::create(['name' => 'C\u00e9dric', 'email' => 'Nacache72@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/15/2003')]);
        User::create(['name' => 'khaled', 'email' => 'khaled.wiq@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('2/4/2000')]);
        User::create(['name' => 'Nicoo', 'email' => 'frizko.gfx@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('11/22/2002')]);
        User::create(['name' => 'prive', 'email' => 'damien21000@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/28/1982')]);
        User::create(['name' => 'Cedwic', 'email' => 'cugnyced@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/21/2004')]);
        User::create(['name' => 'Bryan', 'email' => 'bryan.brach@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/10/1994')]);
        User::create(['name' => 'Himalya', 'email' => 'hiqui07@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('7/22/2007')]);
        User::create(['name' => 'M89', 'email' => 'mohamedbougrara09@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('5/9/2004')]);
        User::create(['name' => 'Regard', 'email' => 'fumey.christel@orange.fr', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('6/1/1971')]);
        User::create(['name' => 'shin', 'email' => 'mamani31@hotmail.fr', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('11/15/1997')]);
        User::create(['name' => 'anonyme', 'email' => 'machinapost@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('4/16/2000')]);
        User::create(['name' => 'Doe', 'email' => 'ohagiman999@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/21/2009')]);
        User::create(['name' => 'Machel\u00e9 Gabriel', 'email' => 'gabrielmachele@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/27/2004')]);
        User::create(['name' => 'Jhon Elia', 'email' => 'programmerzone31@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/22/1995')]);
        User::create(['name' => 'mohsin shahzad', 'email' => 'pearldotpk@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/2/1991')]);
        User::create(['name' => 'Marie', 'email' => 'mvandeburie80200@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('6/29/2000')]);
        User::create(['name' => 'Amadou', 'email' => 'daffmamoune@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/31/1998')]);
        User::create(['name' => 'winy', 'email' => 'yihip24787@laklica.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/5/1996')]);
        User::create(['name' => 'test', 'email' => 'test@consultant.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/1/2009')]);
        User::create(['name' => 'test2021', 'email' => 'test2021@consultant.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/1/2009')]);
        User::create(['name' => 'Adam', 'email' => 'adam.phab26@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/21/2006')]);
        User::create(['name' => 'Habib Ullah', 'email' => 'habib.pk2000000@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/24/1996')]);
        User::create(['name' => 'Quelqu\'un', 'email' => 'tristantheodorebussy@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/8/2007')]);
        User::create(['name' => 'Madysson', 'email' => 'eloidinmadysson@icloud.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('6/7/2006')]);
        User::create(['name' => 'Wilikins', 'email' => 'chrono.gato@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/25/2000')]);
        User::create(['name' => 'Thovi', 'email' => 'anacostlv93@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('8/2/2004')]);
        User::create(['name' => 'Loric', 'email' => 'loric.amizet@my.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/4/2000')]);
        User::create(['name' => 'Mimi', 'email' => 'maitemilhomme@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('2/1/2005')]);
        User::create(['name' => 'Jules', 'email' => 'pilot.jules25@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('4/13/2006')]);
        User::create(['name' => 'jean du Plessis Lesquen', 'email' => 'goygoy@yopmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/25/1998')]);
        User::create(['name' => 'Adammmmm', 'email' => 'mankaiadam145@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/17/2007')]);
        User::create(['name' => 'Melihk8', 'email' => 'melih.toulouse@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/6/2007')]);
        User::create(['name' => 'J\u00e9r\u00e9mie Bartholomeus', 'email' => 'jeremie.bartholomeus@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/8/1999')]);
        User::create(['name' => 'Lissa', 'email' => 'allissamwanza@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('6/23/2007')]);
        User::create(['name' => 'Le Bozec', 'email' => 'lemylb@icloud.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('3/4/2007')]);
        User::create(['name' => 'Paxton39', 'email' => 'paxton39500@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('3/5/2007')]);
        User::create(['name' => 'Valentin0', 'email' => 'zanosprogressive@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/12/1999')]);
        User::create(['name' => 'Michelle', 'email' => 'michelle.corgnetlefeuvre@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('5/15/2000')]);
        User::create(['name' => 'Shad0w', 'email' => 'shadow.95v@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/6/2000')]);
        User::create(['name' => 'Faure', 'email' => 'sonny.faure@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('12/6/2000')]);
        User::create(['name' => 'Douchez', 'email' => 'micheldouchez62@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('12/7/1991')]);
        User::create(['name' => 'Marchal', 'email' => 'coucou.1000@laposte.net', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/5/1978')]);
        User::create(['name' => 'Michaux', 'email' => 'naomimichaux2006@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('8/2/2006')]);
        User::create(['name' => 'Lara', 'email' => 'larastar@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('2/13/1996')]);
        User::create(['name' => 'Lara75', 'email' => 'larastar75@outlook.fr', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('7/14/1997')]);
        User::create(['name' => 'Artysm', 'email' => 'stendjr@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('10/8/1995')]);
        User::create(['name' => 'Losse', 'email' => 'clement.loos31@gmail.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('3/8/2006')]);
        User::create(['name' => 'F\u00e9licie', 'email' => 'felicieman5@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('10/19/2002')]);
        User::create(['name' => 'Elisa prissette', 'email' => 'elisanoxprissette@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('6/20/2006')]);
        User::create(['name' => 'Malo', 'email' => 'vie.deux@yahoo.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/25/2003')]);
        User::create(['name' => 'angie', 'email' => 'lucasbarbaux@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('8/2/2005')]);
        User::create(['name' => 'Alex Benhammou', 'email' => 'guendouzbenhammou@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('3/10/2006')]);
        User::create(['name' => 'Noah', 'email' => 'noahbouttefeux@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('3/10/2007')]);
        User::create(['name' => 'abdelilah', 'email' => 'abdelilahmb5@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/14/1995')]);
        User::create(['name' => 'toti', 'email' => 'toto@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('8/23/1996')]);
        User::create(['name' => 'Gupta', 'email' => 'rohit@codescastle.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/1/1988')]);
        User::create(['name' => 'EASYWEBMOBILE', 'email' => 'contact@easywebmobile.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/9/2000')]);
        User::create(['name' => 'Mirza Mohsin', 'email' => 'mohsin@yopmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('3/18/1995')]);
        User::create(['name' => 'Jhon Doe', 'email' => 'mm5866733@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('12/12/1995')]);
        User::create(['name' => 'Papaz', 'email' => 'papaz191@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/10/1998')]);
        User::create(['name' => 'Salim', 'email' => 'salim.diouf@diderot.org', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('9/11/2002')]);
        User::create(['name' => 'Mohammed Imran', 'email' => 'mit.engg@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('5/10/1989')]);
        User::create(['name' => 'Shahid', 'email' => 'shahid@yopmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('1/5/1987')]);
        User::create(['name' => 'Kana', 'email' => 'thisforatest@yahoo.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('10/21/1993')]);
        User::create(['name' => 'yufu', 'email' => 'syzama123@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('4/24/1998')]);
        User::create(['name' => 'dev', 'email' => 'micronet@consultant.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/10/2008')]);
        User::create(['name' => 'Yannick', 'email' => 'yannickana@yahoo.fr', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/12/1988')]);
        User::create(['name' => 'Kamal ABOUNAIM', 'email' => 'abounaim007@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/10/2000')]);
        User::create(['name' => 'Jackson', 'email' => 'jackson@hotmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('5/17/1990')]);
        User::create(['name' => 'Itaak', 'email' => 'taak-message@outlook.fr', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('6/20/1990')]);
        User::create(['name' => 'yassine stati', 'email' => 'nonev58877@isecv.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/13/1995')]);
        User::create(['name' => 'yanni', 'email' => 'test@test.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('5/4/2002')]);
        User::create(['name' => 'developer', 'email' => 'sthanial2002@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('2/12/1980')]);
        User::create(['name' => 'mohamed yassine', 'email' => 'bobey27184@itwbuy.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/29/1999')]);
        User::create(['name' => 'naruto uzumaki', 'email' => 'necex45651@slowimo.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('2/9/1994')]);
//        User::create(['name' => 'agoumi', 'email' => 'agoumihunter@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('null')]);
//        User::create(['name' => 'bendrioue', 'email' => 'bendrioue@gmail.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('null')]);
        User::create(['name' => 'adambendrioue', 'email' => 'savik77179@moxkid.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/13/1995')]);
        User::create(['name' => 'otmane moghit', 'email' => 'otmanmoghit1994@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('5/13/1994')]);
        User::create(['name' => 'Mira Barton', 'email' => 'zifo@mailinator.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('7/8/1989')]);
        User::create(['name' => 'Yoko Schneider', 'email' => 'kokazuly@mailinator.com', 'password' => Hash::make('password'), 'gender' => '1', 'birth_date' => Carbon::parse('6/7/1992')]);
        User::create(['name' => 'Cl\u00e9ment Puy', 'email' => 'clementerc66@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('1/25/1999')]);
        User::create(['name' => 'Said Bendrioue', 'email' => 'sedosa5308@awinceo.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('5/14/1987')]);
        User::create(['name' => 'David Goff', 'email' => 'towep52456@moxkid.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('9/11/1995')]);
        User::create(['name' => 'moagoumi', 'email' => 'lovtech99@gmail.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('5/27/1999')]);
        User::create(['name' => 'Brendan Caldwell', 'email' => 'sivade9954@seatto.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('7/15/1993')]);
        User::create(['name' => 'hamid', 'email' => 'wixiraj971@w3boats.com', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('5/29/1996')]);
        User::create(['name' => 'Pady', 'email' => 'padydelafou@yahoo.fr', 'password' => Hash::make('password'), 'gender' => '0', 'birth_date' => Carbon::parse('6/11/1995')]);
    }
}
